//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Article
{
    public Article()
    {
        this.KeyWordConnection = new HashSet<KeyWordConnection>();
        this.TypeConnection = new HashSet<TypeConnection>();
    }

    public int id { get; set; }
    public string Title { get; set; }
    public string Author { get; set; }
    public System.DateTime UpateTime { get; set; }
    public string Summary { get; set; }
    public string Link { get; set; }

    public virtual ICollection<KeyWordConnection> KeyWordConnection { get; set; }
    public virtual ICollection<TypeConnection> TypeConnection { get; set; }
}

public partial class Category
{
    public Category()
    {
        this.Option = new HashSet<Option>();
    }

    public int id { get; set; }
    public string Name { get; set; }

    public virtual ICollection<Option> Option { get; set; }
}

public partial class KeyWordConnection
{
    public int id { get; set; }
    public int ArticleId { get; set; }
    public int KeyWordId { get; set; }

    public virtual Article Article { get; set; }
    public virtual KeyWords KeyWords { get; set; }
}

public partial class KeyWords
{
    public KeyWords()
    {
        this.KeyWordConnection = new HashSet<KeyWordConnection>();
    }

    public int id { get; set; }
    public string Name { get; set; }

    public virtual ICollection<KeyWordConnection> KeyWordConnection { get; set; }
}

public partial class Option
{
    public Option()
    {
        this.TypeConnection = new HashSet<TypeConnection>();
    }

    public int id { get; set; }
    public string Name { get; set; }
    public int CategoryId { get; set; }

    public virtual Category Category { get; set; }
    public virtual ICollection<TypeConnection> TypeConnection { get; set; }
}

public partial class sysdiagrams
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class TypeConnection
{
    public int id { get; set; }
    public int ArticleId { get; set; }
    public int OptionId { get; set; }

    public virtual Article Article { get; set; }
    public virtual Option Option { get; set; }
}

public partial class sp_helpdiagramdefinition_Result
{
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class sp_helpdiagrams_Result
{
    public string Database { get; set; }
    public string Name { get; set; }
    public int ID { get; set; }
    public string Owner { get; set; }
    public int OwnerID { get; set; }
}
